version: "3.3"

services:
  qmq-metaserver:
    container_name: qmq-metaserver
    tty: true
    stdin_open: true
    depends_on:
      - qmq-metaserver-db
    image: qunar/qmq-metaserver:0.0.1
    ports:
      - "8080:8080"
    links:
      - qmq-metaserver-db

  qmq-metaserver-db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: qmq-metaserver-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: qmq
    ports:
      - "13306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    volumes_from:
      - apollo-dbdata

  qmq-metaserver-dbdata:
    image: alpine:latest
    container_name: qmq-metaserver-dbdata
    volumes:
      - /var/lib/mysql